-- ══════════════════════════════════════
--  CYBERCUT — Supabase Schema
-- ══════════════════════════════════════

-- Profiles (extends auth.users)
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  nome TEXT NOT NULL,
  email TEXT,
  telefone TEXT,
  cpf TEXT,
  login TEXT,
  perfil TEXT CHECK (perfil IN ('Administrador', 'Barbeiro', 'Atendente', 'Caixa')) DEFAULT 'Atendente',
  status TEXT CHECK (status IN ('Ativo', 'Inativo')) DEFAULT 'Ativo',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Auto-create profile on signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, nome, email)
  VALUES (new.id, COALESCE(new.raw_user_meta_data->>'nome', 'Novo Usuário'), new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE OR REPLACE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- Clientes
CREATE TABLE IF NOT EXISTS clientes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  telefone TEXT,
  email TEXT,
  cpf TEXT,
  nascimento DATE,
  tipo TEXT CHECK (tipo IN ('VIP', 'Regular', 'Novo')) DEFAULT 'Novo',
  endereco TEXT,
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Produtos
CREATE TABLE IF NOT EXISTS produtos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  categoria TEXT CHECK (categoria IN ('Cabelo', 'Barba', 'Pele', 'Ferramentas', 'Outros')),
  preco DECIMAL(10, 2) NOT NULL DEFAULT 0,
  estoque INT DEFAULT 0,
  estoque_minimo INT DEFAULT 0,
  unidade TEXT DEFAULT 'un',
  marca TEXT,
  sku TEXT,
  descricao TEXT,
  emoji TEXT DEFAULT '📦',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Transacoes
CREATE TABLE IF NOT EXISTS transacoes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  descricao TEXT NOT NULL,
  valor DECIMAL(10, 2) NOT NULL,
  data DATE NOT NULL,
  categoria TEXT,
  tipo TEXT CHECK (tipo IN ('entrada', 'saida')) NOT NULL,
  pagamento TEXT DEFAULT 'Pix',
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Servicos
CREATE TABLE IF NOT EXISTS servicos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome TEXT NOT NULL,
  duracao_min INT NOT NULL DEFAULT 30,
  preco DECIMAL(10, 2) NOT NULL DEFAULT 0,
  cor TEXT CHECK (cor IN ('cyan', 'green', 'purple', 'amber', 'pink')) DEFAULT 'cyan'
);

-- Agendamentos
CREATE TABLE IF NOT EXISTS agendamentos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id BIGINT REFERENCES clientes(id) ON DELETE SET NULL,
  barbeiro_id UUID REFERENCES profiles(id) ON DELETE SET NULL,
  servico_id BIGINT REFERENCES servicos(id) ON DELETE SET NULL,
  data DATE NOT NULL,
  hora TIME NOT NULL,
  status TEXT CHECK (status IN ('Confirmado', 'Pendente', 'Cancelado')) DEFAULT 'Pendente',
  observacoes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_agendamentos_data ON agendamentos(data);
CREATE INDEX IF NOT EXISTS idx_agendamentos_barbeiro ON agendamentos(barbeiro_id, data);
CREATE INDEX IF NOT EXISTS idx_transacoes_data ON transacoes(data);
CREATE INDEX IF NOT EXISTS idx_transacoes_tipo ON transacoes(tipo);

-- ══════════════════════════════════════
--  ROW LEVEL SECURITY
-- ══════════════════════════════════════
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY;
ALTER TABLE produtos ENABLE ROW LEVEL SECURITY;
ALTER TABLE transacoes ENABLE ROW LEVEL SECURITY;
ALTER TABLE servicos ENABLE ROW LEVEL SECURITY;
ALTER TABLE agendamentos ENABLE ROW LEVEL SECURITY;

-- Allow full access for development (restrict in production)
CREATE POLICY "Allow all access" ON profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON clientes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON produtos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON transacoes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON servicos FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all access" ON agendamentos FOR ALL USING (true) WITH CHECK (true);

-- ══════════════════════════════════════
--  SEED SERVICOS
-- ══════════════════════════════════════
INSERT INTO servicos (nome, duracao_min, preco, cor) VALUES
  ('Corte', 30, 45.00, 'cyan'),
  ('Barba', 20, 30.00, 'green'),
  ('Combo', 50, 70.00, 'purple'),
  ('Tratamento', 40, 60.00, 'amber'),
  ('Outro', 30, 40.00, 'pink')
ON CONFLICT DO NOTHING;
